name: spelling
on: [push, pull_request]

permissions:
  contents: read

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3
    - name: Spell Check Repo
      uses: crate-ci/typos@master